src/PictureLiker/PictureLiker/Controllers/PictureController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PictureLiker.Authentication;
using PictureLiker.DAL;
using PictureLiker.DAL.Entities;
using PictureLiker.Extensions;
using PictureLiker.Factories;
using PictureLiker.Models;

namespace PictureLiker.Controllers
{   //TODO: Unit Tests
    public class PictureController : Controller
    {
        private readonly IEntityFactory _entityFactory;
        private readonly IUnitOfWork _unitOfWork;
        
        public PictureController(IUnitOfWork unitOfWork, IEntityFactory entityFactory)
        {
            _entityFactory = entityFactory ?? throw new ArgumentNullException(nameof(entityFactory));
            _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            var picture = GetNextAvailableRandomPicture();

            if (picture == null) return View();

            var model = new PictureModel
            {
                Id = picture.Id,
                PictureBytes = picture.Bytes
            };

            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Like(PictureModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));

            if (await IsPictureRated(model.Id))
            {
                return RedirectToAction("Index");
            }

            var preference = _entityFactory.GetPreference(User.GetUserId(), model.Id)
                .SetIsLiked(true);
            await _unitOfWork.PreferenceRepository.AddAsync(preference);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DisLike(PictureModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));

            if (await IsPictureRated(model.Id))
            {
                return RedirectToAction("Index");
            }

            var preference = _entityFactory.GetPreference(User.GetUserId(), model.Id)
                .SetIsLiked(false);
            await _unitOfWork.PreferenceRepository.AddAsync(preference);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = RoleTypes.Administrator)]
        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = RoleTypes.Administrator)]
        [RequestSizeLimit(FileConstraints.MaximumTotalFileSizeInBytes)]
        [ValidateAntiForgeryToken]
        //If uploading large files or the uploading frequency is causing any resource problem, please consider to change the below implementation to upload file(s) 
        //via streaming. For more details, please refer to https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2
        public async Task<IActionResult> UploadAsync(UploadModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));
            if (model.Files == null) throw new ArgumentNullException(nameof(model.Files));

            if (model.Files.Count() > FileConstraints.MaximumNumberOfFilesToBeUploaded)
            {
                ModelState.AddModelError(nameof(model.Files), $"Maximum number of files you can upload is {FileConstraints.MaximumNumberOfFilesToBeUploaded} each time.");

                if (!ModelState.IsValid) return View(nameof(Upload), model);

                return View("Upload", model);
            }

            foreach (var formFile in model.Files)
            {
                if (formFile.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await formFile.CopyToAsync(memoryStream);

                        var picture = _entityFactory.GetPicture().SetBytes(memoryStream.ToArray());
                        await _unitOfWork.PictureRepository.AddAsync(picture);
                    }
                }
            }

            await _unitOfWork.SaveAsync();

            return View("Upload");
        }

        private async Task<bool> IsPictureRated(int pictureId)
        {
            return await _unitOfWork.PreferenceRepository.FirstOrDefaultAsync(p => p.PictureId == pictureId && p.UserId == User.GetUserId()) != null;
        }

        private Picture GetNextAvailableRandomPicture()
        {
            return _unitOfWork.PictureRepository.FromSql(
                $"SELECT TOP 1 {nameof(Picture.Id)}, {nameof(Picture.Bytes)} " +
                "FROM (SELECT * FROM Pictures LEFT JOIN (SELECT PictureId FROM Preferences WHERE UserId = {0}) AS TEMP ON TEMP.PictureId = Id WHERE TEMP.PictureId IS NULL) AS AvailbalePictures " +
                "ORDER BY NEWID()", User.GetUserId())
                .FirstOrDefault();
        }

        public static class FileConstraints
        {
            public const int MaximumNumberOfFilesToBeUploaded = 10;
            public const long MaximumTotalFileSizeInBytes = 3 * 1024 * 1024 * MaximumNumberOfFilesToBeUploaded;
        }
    }
}

src/PictureLiker/PictureLiker/Controllers/PreferenceController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PictureLiker.DAL;
using PictureLiker.Extensions;
using PictureLiker.Models;

namespace PictureLiker.Controllers
{   //TODO: Unit Tests
    public class PreferenceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PreferenceController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index(PreferencesModel model = null)
        {
            model = model ?? new PreferencesModel();

            var userId = User.GetUserId();
            var preferences = _unitOfWork.PreferenceRepository.TakeAtPage(model.SearchCriteria.RequestedPage, PreferencesModel.DefaultRecordsPerPage, p => p.UserId == userId);

            var preferencesWithPicture = preferences.ToList().Select(p => new PicturePreference
            {
                PictureId = p.PictureId,
                IsLiked = p.IsLiked,
                PictureBytes = _unitOfWork.PictureRepository.FirstOrDefault(pic => pic.Id == p.PictureId)?.Bytes
            }).ToArray();

            return View(new PreferencesModel
            {
                PreferencesWithPagination = new DataWithPagination<PicturePreference>
                {
                    ItemsAtCurrentPage = preferencesWithPicture,
                    Page = model.SearchCriteria.RequestedPage,
                    RecordsPerPage = PreferencesModel.DefaultRecordsPerPage,
                    TotalItems = _unitOfWork.PreferenceRepository.LongCount(p => p.UserId == userId)
                }
            });
        }
    }
}

src/PictureLiker/PictureLiker/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using PictureLiker.Authentication
@using PictureLiker.Extensions
@{
    var isUserAuthenticated = User?.Identity?.IsAuthenticated;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PictureLiker</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PictureLiker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (isUserAuthenticated == true)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Picture</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-dark" asp-controller="Picture" asp-action="Index">Gallery</a>
                                    @if (User.HasClaim(ClaimTypes.Role, RoleTypes.Administrator))
                                    {
                                        <a class="dropdown-item text-dark" asp-controller="Picture" asp-action="Upload">Upload New Picture(s)</a>
                                    }
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Preference" asp-action="Index">Preference History</a>
                            </li>
                        }
                    </ul>

                    @if (isUserAuthenticated == true)
                    {
                        <span class="mr-2">Hi, @User.GetName()</span>
                        <form asp-action="LogOutAsync" asp-controller="Account" method="post">
                            <button class="btn btn-outline-secondary" type="submit">Sign Out</button>
                        </form>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PictureLiker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>